# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash2.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtGui import QPixmap, QMovie
from PyQt5 import QtCore, QtGui, QtWidgets


class Splash_window(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(750, 460)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame {\n"
                                           "    background-color: rgb(250, 226, 166);\n"
                                           "    color: rgb(220, 220, 220);\n"
                                           "    border-radius: 10px;\n"
                                           "}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(344, 240, 334, 23))
        self.progressBar.setStyleSheet("QProgressBar {\n"
                                       "\n"
                                       "    background-color: rgb(245, 245, 245);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    border-style: none;\n"
                                       "    border-radius: 5px;\n"
                                       "    text-align: center;\n"
                                       "}\n"
                                       "QProgressBar::chunk{\n"
                                       "    border-radius: 5px;\n"
                                       "    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1,"
                                       " y2:0.523, stop:0 rgba(205, 131, 53, 255), stop:1 rgba(205, 131, 53, 255));\n"
                                       "}")
        self.progressBar.setProperty("value", '15')
        self.progressBar.setObjectName("progressBar")
        self.label_credits = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_credits.setGeometry(QtCore.QRect(540, 270, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(205, 131, 53, 255);")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.label = QtWidgets.QLabel(self.dropShadowFrame)
        self.label.setGeometry(QtCore.QRect(20, 20, 690, 400))
        self.label.setStyleSheet("QLabel{\n"
                                 "    border-radius: 10px;\n"
                                 "}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()

        self.progressBar.raise_()
        self.label_credits.raise_()
        self.verticalLayout.addWidget(self.dropShadowFrame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.label_credits.setText(_translate("SplashScreen",
                                              "<html><head/><body><p><span style=\" font-weight:600;\">Created</span>: Mavlaev D.</p></body></html>"))
